Fix compile error due to unused lambda capture (#50)
This commit fixes the following compilation error:

```
ERROR: /Users/marpaia/git/envoy-filter-example/http-filter-example/BUILD:37:1: C++ compilation of rule '//http-filter-example:http_filter_config' failed (Exit 1)
http-filter-example/http_filter_config.cc:49:14: error: lambda capture 'context' is not used [-Werror,-Wunused-lambda-capture]
    return [&context, config](Http::FilterChainFactoryCallbacks& callbacks) -> void {
             ^
1 error generated.
Target //http-filter-example:envoy failed to build
```

This commit also adds Envoy's `.clang-format` file so that editors don't incorrectly format C++.

Signed-off-by: Mike Arpaia <mike@arpaia.co>